# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fa-docker-codeflo-ra

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2eab369d914d41c8b7ca78722094b4f3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_10d410bf7546462ba9d7c3360e7c18ef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2eab369d914d41c8b7ca78722094b4f3 }}/researcher:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fa-docker-codeflo-ra'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b3c756b8007d41b6a744cc63920822d4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2eab369d914d41c8b7ca78722094b4f3 }}/researcher:${{ github.sha }}'